services:
  liferay:
    image: liferay/dxp:2024.q4.7
    ports:
      - 8080:8080
    volumes:
      - ./liferay/files:/mnt/liferay/files
      - liferay_data:/opt/liferay/data
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      contentwizard:
        condition: service_healthy
  contentwizard:
    build:
      context: contentwizard
      dockerfile: Dockerfile
    image: liferay/ai-tasks-content-wizard-bun:1.0
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail http://contentwizard:3001/ready || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    image: liferay/ai-tasks-elasticsearch:1.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
     - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail http://elasticsearch:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: liferay/ai-tasks-postgres:1.0
    ports:
      - 5433:5432
    volumes:
      -   postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
      - POSTGRES_PASSWORD=L1freay$
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "lportal"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  liferay_data:
  elasticsearch_data:
  postgres_data: