services:
  liferay:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - TARGET_ENV=local
    ports:
      - "8080:8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ~/.config/gcloud/application_default_credentials.json
    volumes:
      - liferay_data:/opt/liferay/data
      - ./build/docker/deploy:/mnt/liferay/deploy
      - ./build/docker/local:/mnt/liferay/files
  ollama:
    image: ollama/ollama:0.5.7
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  ollama-pull--deepseek-r1-7b:
    image: curlimages/curl:latest
    command: >-
      http://ollama:11434/api/pull -d '{"name": "deepseek-r1:7b"}'
    depends_on:
      ollama:
        condition: service_healthy
volumes:
  liferay_data:
  ollama_data:
